general_grasp:
  translation_noise:
    lowerbound: 0.05
    upperbound: 0.15
  interpolation_noise:
    lowerbound: 0.2
    upperbound: 0.5

general_place:
  interpolation_noise:
    lowerbound: 0.2
    upperbound: 0.5